language: go
sudo: false

go:
  - 1.13.x

env:
  - GO111MODULE=on PGPASSWORD=root GOPROXY=https://goproxy.io,https://goproxy.cn,direct

services:
  - mysql
  - postgresql

before_install:
  - mysql -e 'create database `go-admin-test`;'
  - createdb -U postgres go-admin-test

before_script:
  - echo "USE mysql;\nUPDATE user SET authentication_string=PASSWORD('root') WHERE user='root';\nFLUSH PRIVILEGES;\n" | mysql -u root
  - psql -c "ALTER USER postgres WITH PASSWORD 'root';" -U postgres
  - go get -u github.com/rakyll/gotest

script:
  - cd /home/travis/gopath/src/github.com/GoAdminGroup/go-admin && make test